import LayoutComponent from "src/components/layout";
import "./globals.css";
import React from "react";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "Matias Benitez Blog",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={roboto.className + " bg-stone-950 text-stone-200 antialiased"}
    >
      <body>
        <LayoutComponent>{children}</LayoutComponent>
      </body>
    </html>
  );
}
